### ISSUE TITLE
NOVOPlasty.pl missing

### ISSUE THREAD

**Issue by DHatziioanou** [ndierckx/NOVOPlasty#1]
Hi Nicolas,

I thought I would try your software but I don't see the NOVOPlasty.pl or NOVOPlasty_verionX.pl script anywhere here, not sure if you removed it deliberately or its gone missing by mistake but all I can find are the files 
 	.gitignore 	initial commit 	6 months ago
	LICENSE 	Update LICENSE 	2 months ago
	README.md 	Update README.md 	20 days ago
	config.txt 	Update config.txt 	20 days ago

**Comment by ndierckx** [comment]
Hi,


sorry, I just send it personally to anyone who asks because I am changing the version to often.

But I will put definite version online next week


You want me to send it already to you?

And is it for chloroplast or mitochondrial assembly?


________________________________
Van: DHatziioanou <notifications@github.com>
Verzonden: donderdag 7 juli 2016 9:23
Aan: ndierckx/NOVOPlasty
Onderwerp: [ndierckx/NOVOPlasty] NOVOPlasty.pl missing (#1)


Hi Nicolas,

I thought I would try your software but I don't see the NOVOPlasty.pl or NOVOPlasty_verionX.pl script anywhere here, not sure if you removed it deliberately or its gone missing by mistake but all I can find are the files
.gitignore initial commit 6 months ago
LICENSE Update LICENSE 2 months ago
README.md Update README.md 20 days ago
config.txt Update config.txt 20 days ago

-

**Comment by DHatziioanou** [comment]
Hi Nicolas,

I have both a chloroplast and a mitochondria both for the same species and
thought I would try it out. I can wait for the definite version if you're
going to make it available this coming week otherwise it would be very nice
if you could email it to me.

Thanks and all the best,
Diane

DianeHIoanou.at.gmail.com

-- 
Dr Diane Hatziioanou
Greek Mobile: (+30)6909403373
UK Mobile: (+44)7779516625www.linkedin.com/in/dhatziioanou/https://twitter.com/DianeHIoanou

**Comment by ndierckx** [comment]
Hi,

It's best to only use WGS data without extracting any reads nor trimming your reads.
I hope it's WGS, because capture doesn't work?

You can get some explanation on the github page: https://github.com/ndierckx/NOVOPlasty


There are two stands for chloroplast assembly.
I would use 'chloro2' when 'chloro' outputs to many versions or it doesn't circularize.

'chloro2' create separate contigs.

'chloro' will ideally output one or two versions (both one contig) of the assembly: when two, the only difference is the orientation of the region between the inverted repeats.

You will have to check manually what's the correct orientation


also added a seed sequence that works for most chloroplast genomes, if not you can try a sequence from a closer related species.

For plant mitochondria, It's a bit more tricky, you will get contigs, but could be some missing
Have to work on it to improve

Let me know if you have any questions or if it doesn't work, then I will try to help

Greets,

Nicolas



________________________________
Van: DHatziioanou <notifications@github.com>
Verzonden: vrijdag 8 juli 2016 17:38
Aan: ndierckx/NOVOPlasty
CC: Nicolas Dierckxsens; Comment
Onderwerp: Re: [ndierckx/NOVOPlasty] NOVOPlasty.pl missing (#1)

Hi Nicolas,

I have both a chloroplast and a mitochondria both for the same species and
thought I would try it out. I can wait for the definite version if you're
going to make it available this coming week otherwise it would be very nice
if you could email it to me.

Thanks and all the best,
Diane

DianeHIoanou.at.gmail.com

--
Dr Diane Hatziioanou
Greek Mobile: (+30)6909403373
UK Mobile: (+44)7779516625www.linkedin.com/in/dhatziioanou/https://twitter.com/DianeHIoanou


On 8 July 2016 at 18:17, Nicolas Dierckxsens <notifications@github.com>
wrote:

> Hi,
>
>
> sorry, I just send it personally to anyone who asks because I am changing
> the version to often.
>
> But I will put definite version online next week
>
>
> You want me to send it already to you?
>
> And is it for chloroplast or mitochondrial assembly?
>
>
> ________________________________
> Van: DHatziioanou <notifications@github.com>
> Verzonden: donderdag 7 juli 2016 9:23
> Aan: ndierckx/NOVOPlasty
> Onderwerp: [ndierckx/NOVOPlasty] NOVOPlasty.pl missing (#1)
>
>
> Hi Nicolas,
>
> I thought I would try your software but I don't see the NOVOPlasty.pl or
> NOVOPlasty_verionX.pl script anywhere here, not sure if you removed it
> deliberately or its gone missing by mistake but all I can find are the files
> .gitignore initial commit 6 months ago
> LICENSE Update LICENSE 2 months ago
> README.md Update README.md 20 days ago
> config.txt Update config.txt 20 days ago
>
> -
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub<
> https://github.com/ndierckx/NOVOPlasty/issues/1>, or mute the thread<
> https://github.com/notifications/unsubscribe/AOUkFabIakZCPHCJyEpdhIUisLTJlHvSks5qTKl5gaJpZM4JGzmA
> >.
>
> -
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ndierckx/NOVOPlasty/issues/1#issuecomment-231387468>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AQVQBA6PhW3LznMee-OYvIc4ac2gsdrXks5qTmnzgaJpZM4JGzmA>
> .
>

-

**Comment by cassytha** [comment]
Hi Nicolas, Can I get a copy of your NOVOPlasty.pl  script to assemble chloroplast and mitochondira genome? Thanks a lot!

**Comment by ndierckx** [comment]
Hi,
I will put it online this week, if urgent I can send already an older version?
