### ISSUE TITLE
Long read as input

### ISSUE THREAD

**Issue by AmaliT** [ndierckx/NOVOPlasty#108]
Hi

I was wondering if it would be possible to use long reads (such as output from ONT/Pacbio) on novoplasty tool as SE input? Thoughts?

Cheers
Amali

**Comment by ndierckx** [comment]
Hi, 

No that won't work, the error profile is too different and the read lengths vary too much.

Greets

**Comment by jdmontenegro** [comment]
what about corrected long reads or HiFi reads?

**Comment by ndierckx** [comment]
If the reads have around the same length it could maybe work, but I am sure there are better assemblers available for long reads...

**Comment by jdmontenegro** [comment]
I was more concerned about the assembler being aware of circular contigs. I
am not aware of many long read assemblers that are also capable of handling
circular genomes. Any suggestions are more than welcome.

Cheers,

Juan D. Montenegro

**Comment by ndierckx** [comment]
If just started working with long read data recently, so I don't have much experience with it. But the complete organelle genome should be assembled in one contig I think, it can't be that complicated to assemble it with long reads. Did you already tried for your dataset with long read assemblers (and is it for chloroplasts or mitochondrial genomes?)

**Comment by jdmontenegro** [comment]
Well,

I have only tried flye assembler and is producing two non-overlapping
contigs. It looks like. A pretty decent result, but I would like to find
the reads joining both ends of the contigs, but I cannot find them, so
cannot put them together in a single contig.

I have not tried canu or Falcon on this data yet, but I have not found any
obvious reference that it supports circularization. Perhaps that's
something I need to look in the assembly graph rather than the final
assembly.

Thank you Anyway.

Cheers,

Juan D. Montenegro

**Comment by ndierckx** [comment]
You could align all the long reads to those two contigs, maybe some reads that align will overlap, can do that with minimap2
