### ISSUE TITLE
plasmid run parameters

### ISSUE THREAD

**Issue by meono** [ndierckx/NOVOPlasty#11]
Hi,
I am trying NOVOPlasty to assemble plasmid DNA since you mentioned it on a forum post. I already have a seed sequence that we know to be in the plasmid and expect quite good coverage for analysis. I tried following options:
```
Insert size          = 300
Insert size auto     = yes
Read Length          = 150
Type                 = mito (tried chromo as well)
Genome range         = 6500-7500
K-mer                = 24 (tried the default as well)
Insert range         = 2.4 (tried the default as well)
Insert range strict  = 1.2
Paired/Single        = PE
Coverage Cut off     = 250 (tried 100 and the default as well)
Extended log         = 1
```
I haven't managed to go beyond seed retrieval phase. Do you have any suggestions/corrections for the parameters? Another question is, how much trouble foreign DNA would cause - as I expect to have a fair amount of that too.
Thanks

**Comment by ndierckx** [comment]
Hi,

If you are stuck at the seed retrieval, the only parameter that has an influence is the kmer. Since 24 is already low, you must have insufficient coverage or an incorrect seed. Could you give some more info about your data, is it wgs, is it paired end, and maybe send me the structure of a read id from your data file. And how long is your seed sequence?

For the other parameters, you should keep type at chloro (not chromo), you genome range is way too low for a chloroplast, and put insert range and coverage cut off back to default

**Comment by meono** [comment]
thanks for the quick response.
You are right, I may have gone over-ambitious with the seed. I think the sequence had incorrect bits. Tried the parameters you suggested and reducing the seed to a more conservative sequence - size to ~700bp - which did the trick. I have a contig of ~3600bp now.
K-mer = 36 lead to ~4000bp.
this was a plasmid-only, illumina run, paired-end reads.

**Comment by ndierckx** [comment]
If the coverage is low, you need a good seed. So you have capture DNA then?
If so, NOVOPlasty will only work well if you have no large gaps in coverage, which is rarely the case with capture DNA. I developed it for WGS data, so I wouldn't expect a complete chloroplast genome.

**Comment by meono** [comment]
actually, i'd say it worked quite well for the data I have. It was quite easy to use too.
thanks again for the help!
