### ISSUE TITLE
How to deal with degenerate bases?

### ISSUE THREAD

**Issue by yangyang9608** [ndierckx/NOVOPlasty#112]
Hello~ I had some confusing. If the fasta file include the degenerate bases, how to deal with degenerate bases? Can I remove them? And I wonder to know how to produce the degenerate bases. And I had met the another problem that the fasta file has termination codon(*). What could I do? I would very appreciate it if you could reply me.

**Comment by ndierckx** [comment]
If you remove those bases, you create a gap in the sequence, where there should be a base.
You can remove the *, for more info check the "Interpretation and post-processing" in the readme, it's explained there

**Comment by yangyang9608** [comment]
Okay,I can understand your meaning. So if I filter the reads before assembly, this problem may not arise? I have tried the version2.5.7 and version 3.7, which I used the same *.fq.gz and the same seed file Seed_RUBP_cp.fasta. The former result fasta did not contain degenerate base in the same position,  but the latter fasta had the degenerate base. I can't figure out the scripts ,so I wonder if the assembly process is random. I don't know much about this filed. Thank you very much~

**Comment by ndierckx** [comment]
I wouldn't call it degenerate bases, it are ambiguous bases. It means that the assembler couldn't determine the base with 100% accuracy, usually caused by homologous regions in the nuclear region or by heteroplasmy. So I wouldn't filter the reads. I don't know why one ambiguous base is such a problem, it is quite common in assemblies. You can always align you reads to the assembly and manually check which base will most likely be correct

**Comment by yangyang9608** [comment]
Okay, I see. Thanks a lot~
