### ISSUE TITLE
What's the difference between {Seed Input} and {Reference sequence}

### ISSUE THREAD

**Issue by kuangzhuoran** [ndierckx/NOVOPlasty#175]
Hi !
I try to assemble animal mitochondrion (Circetidae and Nematoda，The latter has not yet been identified as a species)，and I checked the seed that came with the software and found that it was from a plant ，Can it be used for mitochondrial assembly in animals？
I download Model species's mitochondrion, complete genome from NCBI, So Do I need to set  {Seed Input} and {Reference sequence} to be the same？

Thanks！
kzr

**Comment by ndierckx** [comment]
Hi,

The seed is indeed only for chloroplast assemblies.
I didn't add a mitochondrion sequence because it is very flexible.

You can add the COI gene from the mitochondrion for example
I would not use a complete mitochondrial sequence, because it will just take the first 100 bp sequence to find a read.
And if the first 100 bp is a repetitive region, it would a bad region to start an assembly.

Maybe i will add a seed for mitochondrial genomes too, but best to take a gene sequence of a not too distant species

The reference sequence is rarely used in mitochodrial assembly because it is always de novo, but can resolve the inverted repeat in chloropalst genomes, but you can add it, it is always possible it can help resolving a complex region

**Comment by kuangzhuoran** [comment]
Thanks you very much !
I think I get it ！

best regards
kzr
