### ISSUE TITLE
Orientation problem of some chloroplast genome

### ISSUE THREAD

**Issue by Mohammada1994** [ndierckx/NOVOPlasty#192]
Hello Nicolas,

I did the assembly of chloroplast genomes for some Boraginaceae species, in a few species, I got an orientation problem where the rbcl gene position is within the circular shape in a clockwise direction, and the atpB and atpE genes position is are outside the circular shape in the anti-clockwise direction (please see the picture), and this is a different result from most assemblies of chloroplast genomes that have been published !!!. (usually, the rbcl gene is outside the circular shape and in the anti-clockwise direction while the atpB and atpE genes are within the circular shape and in a clockwise direction)

I am using Chlorobox to draw the gene map after Novoplast finishes the assembly, this issue happened with only two of 7 samples, the two samples are from the same family !!!, I change the seed and reference many times and still got the same result.

![rbcl and atpB and atpE](https://user-images.githubusercontent.com/107177899/172804215-e65f9020-00e7-4ec9-be14-a0c4f1de2f0c.jpg)

Any idea what I need to fix this?

Thanks!

**Comment by ndierckx** [comment]
Hi,

I have not much experience with the annotation of chloroplast genomes, so can't help much there.
Are you sure this is not correct, it is not because it usually different, it is incorrect..

Have you realigned the reads in the region, then you can visually inspect if there are inconsistencies or verify with other assembly tools...
