### ISSUE TITLE
how to correct the direction of IR

### ISSUE THREAD

**Issue by zhangnfda** [ndierckx/NOVOPlasty#21]
Thanks for developing this great tool, it is very helpful.
I tried with my own data, I can get the circular sequence of chloroplast genome for most species.
However, I found that sometimes the direction of the small single copy region (SSR) is reverse when compared with the chloroplast genome of closely related species. 
My questions is when I have this problem, how can I correct the reversion and how to define the boundary of the SSC. 
Ning

**Comment by ndierckx** [comment]
Have you tried to use the genome of the close related species as reference?
It should follow the same orientation if you do

**Comment by zhangnfda** [comment]
For one sample, I use rbcL and the cp genome of the closely related species respectively, I got the same  orientation. I usually use rbcL as the seed because it is easy to find in the GenBank. You mean the cp genome of closely related species works better? 
Ning

**Comment by zhangnfda** [comment]
Another question is I noticed that you mentioned "As an output you get two fasta files, the only difference between them is the orientation of the region between the inverted repeats." But I just got one  complete assembly in the file Circularized_assembly_xxxxx.fasta.

**Comment by ndierckx** [comment]
The seed doesn't matter, you can use whatever species.
I mean as a reference sequence, it is an option in the config file (unless you use an old version)

And sometimes there is only one output because there is no IR or there are some differences between the two IR's. But I would not trust every NCBI sequence as correct, I found plenty of mistakes already.

If you are certain that the region between the inverted repeat has the wrong orientation, try to give a close reference.
