### ISSUE TITLE
Memory Allocation

### ISSUE THREAD

**Issue by TARobison** [ndierckx/NOVOPlasty#3]
Is it possible to run this with parallel cores?

**Comment by ndierckx** [comment]
For the moment not, but planning to do it for a new version for larger genomes.
I could also add it to NOVOPlasty, but was not planning it because I don't think it will speed up the process a lot..
But do you have memory problems? If it is because you have huge data files, you can just subsample because it won't reduce the assembly quality..

**Comment by TARobison** [comment]
I am having memory problems. Forgive my ignorance, but what is the best way to go about sub sampling?

**Comment by ndierckx** [comment]
What kind of data do you have and how much memory available?
There are many scripts available or can write one yourself..
Could try this one: http://qiime.org/scripts/subsample_fasta.html

**Comment by TARobison** [comment]
The data are derived from 300bp libraries and HiSeq 125 bp PE. have 80gb available memory.

**Comment by ndierckx** [comment]
Then you have to subsample for sure, generally 6 GB is enough to assemble a chloroplast :)
Try to subsample 20%, then you still more then enough coverage..

**Comment by TARobison** [comment]
I will give this a shot. Thank you very much!
