### ISSUE TITLE
Read Length when using trimmed reads

### ISSUE THREAD

**Issue by scrameri** [ndierckx/NOVOPlasty#5]
Hi Nicolas,

Very handy tool, thank you very much!

I tried the tool with the raw data in .fastq format, and both chloro and chloro2 algorithms could not circularize the organelle (got a contig ~40kb long). Just to try, I quality filtered the raw data even if you do not recommend it.

Now I'm not sure how to set the **Read Length** argument when using trimmed reads instead of raw reads, and I have these hypothetical questions:

- does the program require that all reads have the same length?
- does it make sense to input the e.g. mean read length?
- does it make sense to trim all reads to the same length?

Thank you and merry Christmas
Simon

**Comment by ndierckx** [comment]
Hi,

Same read length is not required (although it helps), I would set the read length to the original length of the reads, definitely don't trim any further. Trimming creates gaps in the assembly because Illumina has systemic errors, so same regions will be trimmed.. I don't get why trimming is ever invented :)
But why you use quality trimmed reads? Have you tried with the raw reads?

Greets,

Nicolas
